require("calista.plugins-setup")
require("calista.core.options")
require("calista.core.keymaps")
require("calista.core.colorscheme")
require("calista.plugins.comment")
-- require("calista.plugins.nvim-tree")
require("calista.plugins.lualine")
require("calista.plugins.telescope")
-- require("calista.plugins.nvim-cmp")
-- require("calista.plugins.lsp.mason")
-- require("calista.plugins.lsp.lspsaga")
-- require("calista.plugins.lsp.lspconfig")
-- require("calista.plugins.lsp.null-ls")
require("calista.plugins.autopairs")
require("calista.plugins.neotree")
require("calista.plugins.lsp")
require("calista.plugins.refactoring")
require("calista.plugins.undotree")
require("calista.plugins.treesitter")
require("calista.plugins.gitsigns")
require("calista.plugins.toggleterm")
