-- require("calista.plugins-setup")
-- require("calista.core.options")
-- require("calista.core.keymaps")
-- require("calista.core.colorscheme")
-- require("calista.plugins.comment")
-- require("calista.plugins.lualine")
-- require("calista.plugins.telescope")
-- require("calista.plugins.nvim-cmp")
-- require("calista.plugins.lsp.mason")
-- require("calista.plugins.lsp.lspconfig")
-- require("calista.plugins.autopairs")
-- require("calista.plugins.treesitter")
-- require("calista.plugins.gitsigns")
-- require("calista.plugins.colorizer")
-- require("calista.plugins.toggleterm")
-- require("calista.plugins.leap")
-- require("calista.plugins.mdx-file")
-- require("calista.plugins.blankline")
-- require("calista.plugins.neo-tree")

-- lazy
require("calista.core")
require("calista.lazy")
